# Generated by Django 4.0.2 on 2022-04-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.FileField(default='default.pdf', upload_to='media/files'),
        ),
    ]
