# Generated by Django 4.0.2 on 2022-04-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_profilepic_profilepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilepic',
        ),
    ]
