# Generated by Django 4.0.2 on 2022-04-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_copy', '0002_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='about',
            field=models.TextField(default=' ', max_length=50),
        ),
    ]
